### ISSUE TITLE
Adding neotoma occurrence data?

### ISSUE THREAD

**Issue by SimonGoring** [ropenscilabs/occurrence-manual#1]

**Comment by sckott** [comment]
thanks simon. however, i'm not quite sure how i'm going to structure the chapters yet, whether they'll be a chapter for each pkg, or if they'll be grouped thematically or so

**Comment by SimonGoring** [comment]
Okay, just let me know.  We have our new API up for the EarthLifeConsortium too.  [ELC site is here](http://earthlifeconsortium.org/), and on [GitHub here](https://github.com/EarthLifeConsortium/elc_api).  We're wrapping the API into a package, let me know if we can do anything to align the pkg vignette with your stuff.

**Comment by sckott** [comment]
thanks simon, will let you know when I have a better idea of structure here

**Comment by SimonGoring** [comment]
Closing this issue for now.
